classes:
  fighter:
    description: Invisible when sneaking. Starts with enchanted iron armor, iron sword, shield, and bow.
    flags:
      invisibilitySneak: true
    items:
      IRON_HELMET:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
          THORNS: 3
          PROTECTION: 3
      IRON_CHESTPLATE:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
          THORNS: 3
          PROTECTION: 3
      IRON_BOOTS:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
          THORNS: 3
          PROTECTION: 3
      IRON_LEGGINGS:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
          THORNS: 3
          PROTECTION: 3
      SHIELD:
        count: 1
        enchantments:
          unbreaking: 3
          mending: 1
      IRON_SWORD:
        enchantments:
          unbreaking: 3
          looting: 3
          sharpness: 3
      BOW:
        enchantments:
          infinity: 1
          power: 3
          unbreaking: 3
          flame: 1
  builder:
    description: Resistant to damage. Starts with a large amount of building blocks.
    flags:
      resistance: true
    items:
      BIRCH_PLANKS:
        count: 64
      SPRUCE_PLANKS:
        count: 64
      OAK_PLANKS:
        count: 64
      COBBLESTONE:
        count: 64
      BIRCH_WOOD:
        count: 64
      REDSTONE:
        count: 64
      IRON_PICKAXE:
        enchantments:
          MENDING: 1
          unbreaking: 3
        count: 1
      IRON_AXE:
        enchantments:
          MENDING: 1
          unbreaking: 3
        count: 1
      IRON_SHOVEL:
        enchantments:
          MENDING: 1
          unbreaking: 3
        count: 1
      PISTON:
        count: 32
      STICKY_PISTON:
        count: 32
      TORCH:
        count: 64
      BRICKS:
        count: 64
      GLASS:
        count: 64
      WHITE_WOOL:
        count: 64
      WHITE_BED:
        count: 4
      LEATHER_HELMET:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
      LEATHER_CHESTPLATE:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
      LEATHER_LEGGINGS:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
      LEATHER_BOOTS:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
  farmer:
    description: Can reap/sow multiple plants at once. starts with hoe, seeds, bone meal, eggs, and buckets.
    flags:
      plantMany: true
    items:
      CHICKEN_SPAWN_EGG:
        count: 10
      COW_SPAWN_EGG:
        count: 10
      SHEARS:
        enchantments:
          unbreaking: 3
          mending: 1
          efficiency: 3

      MELON_SEEDS:
        count: 64
      PUMPKIN_SEEDS:
        count: 64
      WHEAT_SEEDS:
        count: 64
      CARROTS:
        count: 64
      DIAMOND_HOE:
        count: 1
        enchantments:
          efficiency: 5
          unbreaking: 3
          fortune: 3
          silk_touch: 1
          mending: 1
      BONE_MEAL:
        count: 64
      DIRT:
        count: 64
      SAND:
        count: 64
      BUCKET:
        count: 4
      LEATHER_HELMET:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
      LEATHER_CHESTPLATE:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
      LEATHER_LEGGINGS:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
      LEATHER_BOOTS:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
  explorer:
    description: Moves faster and jump higher. Start with wings, fishing rod, map, spyglass, and leather armor.
    flags:
      speed: true
    items:
      IRON_AXE:
        count: 1
      OAK_BOAT:
        count: 1
      ELYTRA:
        count: 1
      FIREWORK_ROCKET:
        count: 64
      FISHING_ROD:
        count: 1
      MAP:
        count: 1
      SPYGLASS:
        count: 1
      COMPASS:
        count: 1
      FLINT_AND_STEEL:
        count: 1
      TORCH:
        count: 32
      WHITE_BED:
        count: 1
      LEATHER_HELMET:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
      LEATHER_CHESTPLATE:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
      LEATHER_LEGGINGS:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
      LEATHER_BOOTS:
        enchantments:
          MENDING: 1
          UNBREAKING: 3

  miner:
    description: Mines faster. Starts with pickaxe, redstone, rails, and leather armor.
    flags:
      haste: true
    items:
      MINECART:
        count: 1
      POWERED_RAIL:
        count: 32
      RAIL:
        count: 64
      REDSTONE:
        count: 64
      TORCH:
        count: 64
      WHITE_BED:
        count: 1
      IRON_PICKAXE:
        enchantments:
          UNBREAKING: 3
          MENDING: 1
          FORTUNE: 3
          EFFICIENCY: 3
      IRON_SHOVEL:
        enchantments:
          UNBREAKING: 3
          MENDING: 1
          EFFICIENCY: 3
      IRON_AXE:
        count: 1
      LEATHER_HELMET:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
      LEATHER_CHESTPLATE:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
      LEATHER_LEGGINGS:
        enchantments:
          MENDING: 1
          UNBREAKING: 3
      LEATHER_BOOTS:
        enchantments:
          MENDING: 1
          UNBREAKING: 3